### ISSUE TITLE
gun game mod

### ISSUE THREAD

**Issue by Pablocavola** [BentUndJustus/MW2_gungame#1]

**Comment by ju57u5** [comment]
?

**Comment by ToxinSnake** [comment]
good request, please implement

**Comment by Pablocavola** [comment]
I definitely need to learn how to use github. I thought I was saving it or adding it to favorites. Sorry for that

**Comment by ju57u5** [comment]
No worries.
That is what the star in the upper right corner is for:

![image](https://user-images.githubusercontent.com/2545457/81091579-b4d6c480-8eff-11ea-9578-e143e6c128d6.png)
